<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find legged_xiaomigo_description)/urdf/common/transmission.xacro"/>

    <xacro:macro name="leg" params="prefix mirror mirror_dae front_hind front_hind_dae *origin">

        <joint name="${prefix}_HAA" type="revolute">
            <xacro:insert_block name="origin"/>
            <parent link="base"/>
            <child link="${prefix}_hip"/>
            
            <xacro:if value="${(prefix == 'RF')}">
                <axis xyz="1 0 0"/>
            </xacro:if>
            <xacro:if value="${(prefix == 'LF')}">
                <axis xyz="1 0 0"/>
            </xacro:if>
            <xacro:if value="${(prefix == 'RH')}">
                <axis xyz="1 0 0"/>
            </xacro:if>
            <xacro:if value="${(prefix == 'LH')}">
                <axis xyz="1 0 0"/>
            </xacro:if>
            
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${hip_min}"
                       upper="${hip_max}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${-hip_max}"
                       upper="${-hip_min}"/>
            </xacro:if>
        </joint>

        <link name="${prefix}_hip">
            <visual>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                    <!-- <origin rpy="${pi} 0 0" xyz="0 0 0"/> -->

                </xacro:if>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                    <origin rpy="0 0 ${pi}" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                    <origin rpy="0 0 ${pi}" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                        <mesh filename="package://legged_xiaomigo_description/meshes/$(arg robot_type)/FL_hip_link.STL" scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                        <mesh filename="package://legged_xiaomigo_description/meshes/$(arg robot_type)/FR_hip_link.STL" scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                        <mesh filename="package://legged_xiaomigo_description/meshes/$(arg robot_type)/FR_hip_link.STL" scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                        <mesh filename="package://legged_xiaomigo_description/meshes/$(arg robot_type)/FL_hip_link.STL" scale="1 1 1"/>
                    </xacro:if>

                </geometry>
                <material name="white"/>
            </visual>

            <collision>
                <origin rpy="${pi/2.0} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${hip_length}" radius="${hip_radius}"/>
                </geometry>
            </collision>

            <inertial>
                <origin rpy="0 0 0" xyz="${hip_com_x*front_hind} ${hip_com_y*mirror} ${hip_com_z}"/>
                <mass value="${hip_mass}"/>
                <inertia
                        ixx="${hip_ixx}" ixy="${hip_ixy*mirror*front_hind}" ixz="${hip_ixz*front_hind}"
                        iyy="${hip_iyy}" iyz="${hip_iyz*mirror}"
                        izz="${hip_izz}"/>
            </inertial>
        </link>

        <joint name="${prefix}_HFE" type="revolute">
        <!-- c -->
            <!-- <origin rpy="0 0 0" xyz="0 ${thigh_offset*mirror} 0"/> -->
            <origin rpy="0 0.0 0" xyz="0 ${thigh_offset*mirror} 0"/>

            <parent link="${prefix}_hip"/>
            <child link="${prefix}_thigh"/>
            <!-- <axis xyz="0 -1 0"/> -->
            <axis xyz="0 1 0"/>

            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}" lower="${thigh_min}"
                   upper="${thigh_max}"/>
        </joint>

        <link name="${prefix}_thigh">

            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <xacro:if value="${mirror_dae == True}">
                        <mesh filename="package://legged_xiaomigo_description/meshes/$(arg robot_type)/FL_thigh_link.STL"
                              scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${mirror_dae == False}">
                        <mesh filename="package://legged_xiaomigo_description/meshes/$(arg robot_type)/FR_thigh_link.STL"
                              scale="1 1 1"/>
                    </xacro:if>
                </geometry>
                <material name="white"/>
            </visual>
            
            <collision>
                <origin rpy="0 ${pi/2.0} 0" xyz="0 0 ${-thigh_length/2.0}"/>
                <!-- <origin rpy="0 ${pi/2.0+0.1} 0" xyz="0 0 ${-thigh_length/2.0}"/> -->
                <geometry>
                    <box size="${thigh_length} ${thigh_width} ${thigh_height}"/>
                </geometry>
            </collision>

            <collision>
                <origin rpy="${pi/2.0} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${thigh_shoulder_length}" radius="${thigh_shoulder_radius}"/>
                </geometry>
            </collision>

            <inertial>
                <origin rpy="0 0 0" xyz="${thigh_com_x} ${thigh_com_y*mirror} ${thigh_com_z}"/>
                <mass value="${thigh_mass}"/>
                <inertia
                        ixx="${thigh_ixx}" ixy="${thigh_ixy*mirror}" ixz="${thigh_ixz}"
                        iyy="${thigh_iyy}" iyz="${thigh_iyz*mirror}"
                        izz="${thigh_izz}"/>
            </inertial>
        </link>

        <joint name="${prefix}_KFE" type="revolute">
        <!-- cc -->
            <origin rpy="0 0 0" xyz="0 0 ${-thigh_length}"/>

            <parent link="${prefix}_thigh"/>
            <child link="${prefix}_calf"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${calf_min}" upper="${calf_max}"/>
        </joint>

        <link name="${prefix}_calf">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://legged_xiaomigo_description/meshes/$(arg robot_type)/FL_calf_link.STL" scale="1 1 1"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin rpy="0 ${pi/2.0} 0" xyz="0 0 ${-calf_length/2.0}"/>
                <geometry>
                    <box size="${calf_length} ${calf_width} ${calf_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${calf_com_x} ${calf_com_y} ${calf_com_z}"/>
                <mass value="${calf_mass}"/>
                <inertia
                        ixx="${calf_ixx}" ixy="${calf_ixy}" ixz="${calf_ixz}"
                        iyy="${calf_iyy}" iyz="${calf_iyz}"
                        izz="${calf_izz}"/>
            </inertial>
        </link>

        <joint name="${prefix}_foot_fixed" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 ${-(calf_length)}"/>
            <parent link="${prefix}_calf"/>
            <child link="${prefix}_FOOT"/>
        </joint>

        <link name="${prefix}_FOOT">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${foot_radius}"/>
                    <!-- <mesh filename="package://legged_xiaomigo_description/meshes/$(arg robot_type)/FL_toe_link.STL" scale="1 1 1"/> -->
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${foot_radius}"/>
                </geometry>
            </collision>
            <!-- <inertial>
                <mass value="${foot_mass}"/>
                <inertia
                        ixx="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" ixy="0.0" ixz="0.0"
                        iyy="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" iyz="0.0"
                        izz="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}"/>
            </inertial> -->
            <!-- <inertial>
                <mass value="${0.0}"/>
                <inertia
                        ixx="0.0" ixy="0.0" ixz="0.0"
                        iyy="0.0" iyz="0.0"
                        izz="0.0"/>
            </inertial> -->
            <inertial>
                <mass value="${foot_mass}"/>
                <origin rpy="0 0 0" xyz="${foot_com_x} ${foot_com_y} ${foot_com_z}"/>
                <inertia
                        ixx="${foot_ixx}" ixy="${foot_ixy}" ixz="${foot_ixz}"
                        iyy="${foot_iyy}" iyz="${foot_iyz}"
                        izz="${foot_izz}"/>
            </inertial>

        </link>

        <gazebo reference="${prefix}_foot_fixed">
            <disableFixedJointLumping>true</disableFixedJointLumping>
        </gazebo>

        <xacro:leg_transmission name="${prefix}"/>
    </xacro:macro>
</robot>
